In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR = '/content/drive/MyDrive/EduAI_Models/summarizer'
os.makedirs(SAVE_DIR, exist_ok=True)
print(f'Model will be saved to: {SAVE_DIR}')

Mounted at /content/drive
Model will be saved to: /content/drive/MyDrive/EduAI_Models/summarizer

In [ ]:
!pip install --upgrade transformers accelerate datasets evaluate rouge_score sentencepiece -q

import transformers
print(f'Transformers version: {transformers.__version__}')

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 44.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 20.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 520.7/520.7 kB 19.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 11.7 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done
Transformers version: 5.3.0

In [ ]:
from datasets import load_dataset, concatenate_datasets

# Loading datasets
print('Loading arxiv dataset...')
arxiv = load_dataset('ccdv/arxiv-summarization', trust_remote_code=True)
arxiv_train = arxiv['train'].select(range(5000))
arxiv_val = arxiv['validation'].select(range(500))

print('Loading CNN/DailyMail dataset...')
cnn = load_dataset('cnn_dailymail', '3.0.0')
cnn_train = cnn['train'].select(range(5000))
cnn_val = cnn['validation'].select(range(500))

print(f'Arxiv train: {len(arxiv_train)}, val: {len(arxiv_val)}')
print(f'CNN train: {len(cnn_train)}, val: {len(cnn_val)}')

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'ccdv/arxiv-summarization' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'ccdv/arxiv-summarization' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

Loading arxiv dataset...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

section/train-00000-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00001-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00002-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00003-of-00015.parquet:   0%|          | 0.00/227M [00:00<?, ?B/s]

section/train-00004-of-00015.parquet:   0%|          | 0.00/226M [00:00<?, ?B/s]

section/train-00005-of-00015.parquet:   0%|          | 0.00/227M [00:00<?, ?B/s]

section/train-00006-of-00015.parquet:   0%|          | 0.00/229M [00:00<?, ?B/s]

section/train-00007-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00008-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00009-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00010-of-00015.parquet:   0%|          | 0.00/229M [00:00<?, ?B/s]

section/train-00011-of-00015.parquet:   0%|          | 0.00/231M [00:00<?, ?B/s]

section/train-00012-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00013-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00014-of-00015.parquet:   0%|          | 0.00/235M [00:00<?, ?B/s]

section/validation-00000-of-00001.parque(…):   0%|          | 0.00/105M [00:00<?, ?B/s]

section/test-00000-of-00001.parquet:   0%|          | 0.00/105M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/203037 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6436 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6440 [00:00<?, ? examples/s]

Loading CNN/DailyMail dataset...

README.md: 0.00B [00:00, ?B/s]

3.0.0/train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

3.0.0/validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

3.0.0/test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Arxiv train: 5000, val: 500
CNN train: 5000, val: 500

In [ ]:
def format_arxiv(example):
    return {
        'input_text': 'Summarize the following academic text:\n' + example['article'][:2000],
        'target_text': example['abstract'][:500]
    }

def format_cnn(example):
    return {
        'input_text': 'Summarize the following text:\n' + example['article'][:2000],
        'target_text': example['highlights'][:500]
    }

arxiv_train = arxiv_train.map(format_arxiv, remove_columns=arxiv_train.column_names)
arxiv_val = arxiv_val.map(format_arxiv, remove_columns=arxiv_val.column_names)
cnn_train = cnn_train.map(format_cnn, remove_columns=cnn_train.column_names)
cnn_val = cnn_val.map(format_cnn, remove_columns=cnn_val.column_names)

train_dataset = concatenate_datasets([arxiv_train, cnn_train]).shuffle(seed=42)
val_dataset = concatenate_datasets([arxiv_val, cnn_val]).shuffle(seed=42)

print(f'Combined train: {len(train_dataset)}, val: {len(val_dataset)}')
print(f'\nSample input (first 200 chars): {train_dataset[0]["input_text"][:200]}')
print(f'\nSample target (first 200 chars): {train_dataset[0]["target_text"][:200]}')

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Combined train: 10000, val: 1000

Sample input (first 200 chars): Summarize the following text:
(Entertainment Weekly) -- The Disney family film update, "Race to Witch Mountain," won the weekend box office in fine fashion, grossing $25 million according to Sunday's

Sample target (first 200 chars): This is the second best opening ever for a movie fronted by Dwayne Johnson .
"Watchmen" dropped a hefty 67 percent from its big opening last weekend .
"The Last House on the Left" came in at No. 3 wit

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = 'google/flan-t5-base'

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print(f'Model loaded: {MODEL_NAME}')
print(f'Parameters: {sum(p.numel() for p in model.parameters()):,}')

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Model loaded: google/flan-t5-base
Parameters: 247,577,856

In [ ]:
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 200

def tokenize_function(example):
    model_inputs = tokenizer(
        example['input_text'],
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding='max_length'
    )

    labels = tokenizer(
        example['target_text'],
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
        padding='max_length'
    )

    labels_ids = [
        token if token != tokenizer.pad_token_id else -100
        for token in labels['input_ids']
    ]

    model_inputs['labels'] = labels_ids
    return model_inputs

print('Tokenizing train dataset...')
tokenized_train = train_dataset.map(tokenize_function, batched=False, remove_columns=train_dataset.column_names)

print('Tokenizing validation dataset...')
tokenized_val = val_dataset.map(tokenize_function, batched=False, remove_columns=val_dataset.column_names)

print(f'Tokenized train: {len(tokenized_train)}, val: {len(tokenized_val)}')

Tokenizing train dataset...

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Tokenizing validation dataset...

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenized train: 10000, val: 1000

In [ ]:
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, DataCollatorForSeq2Seq

training_args = Seq2SeqTrainingArguments(
    output_dir=SAVE_DIR,

    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=3e-5,
    weight_decay=0.01,
    warmup_steps=200,
    max_grad_norm=1.0,

    eval_strategy='epoch',
    predict_with_generate=True,
    generation_max_length=MAX_TARGET_LENGTH,

    save_strategy='epoch',
    save_total_limit=3,
    load_best_model_at_end=True,
    metric_for_best_model='eval_loss',

    fp16=False,
    bf16=False,

    logging_steps=50,
    report_to='none',
)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    data_collator=data_collator,
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

TrainOutput(global_step=7500, training_loss=2.439717536417643, metrics={'train_runtime': 7284.851, 'train_samples_per_second': 4.118, 'train_steps_per_second': 1.03, 'total_flos': 2.054272057344e+16, 'train_loss': 2.439717536417643, 'epoch': 3.0})

In [ ]:
import glob
checkpoints = sorted(glob.glob(f'{SAVE_DIR}/checkpoint-*'))
if checkpoints:
  latest = checkpoints[-1]
  print(f'Resuming from: {latest}')
  trainer.train(resume_from_checkpoint=latest)
else:
  print('No checkpoints found.')

Resuming from: /content/drive/MyDrive/EduAI_Models/summarizer/checkpoint-7500

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].
There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

In [ ]:
import evaluate
import numpy as np
from tqdm import tqdm

rouge = evaluate.load('rouge')

print('Generating summaries for ROUGE evaluation...')
predictions = []
references = []

eval_samples = val_dataset.select(range(min(200, len(val_dataset))))

model.eval()
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

for i in tqdm(range(len(eval_samples))):
    input_text = eval_samples[i]['input_text']
    reference = eval_samples[i]['target_text']

    inputs = tokenizer(input_text, max_length=MAX_INPUT_LENGTH, truncation=True, return_tensors='pt').to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=MAX_TARGET_LENGTH,
            min_length=30,
            num_beams=4,
            length_penalty=1.0,
            no_repeat_ngram_size=3,
            early_stopping=True
        )

    prediction = tokenizer.decode(outputs[0], skip_special_tokens=True)
    predictions.append(prediction)
    references.append(reference)

# ROUGE
results = rouge.compute(predictions=predictions, references=references)

print('\n=========================================')
print('      ROUGE EVALUATION RESULTS')
print('=========================================')
print(f'ROUGE-1: {results["rouge1"]:.4f}')
print(f'ROUGE-2: {results["rouge2"]:.4f}')
print(f'ROUGE-L: {results["rougeL"]:.4f}')
print(f'ROUGE-Lsum: {results["rougeLsum"]:.4f}')
print('=========================================')

# Save results
with open(f'{SAVE_DIR}/rouge_results.txt', 'w') as f:
    for k, v in results.items():
        f.write(f'{k}: {v:.4f}\n')
print(f'Results saved to {SAVE_DIR}/rouge_results.txt')

Downloading builder script: 0.00B [00:00, ?B/s]

Generating summaries for ROUGE evaluation...

100%|██████████| 200/200 [08:55<00:00,  2.68s/it]

=========================================
      ROUGE EVALUATION RESULTS
=========================================
ROUGE-1: 0.3421
ROUGE-2: 0.1262
ROUGE-L: 0.2281
ROUGE-Lsum: 0.2797
=========================================
Results saved to /content/drive/MyDrive/EduAI_Models/summarizer/rouge_results.txt

In [ ]:
print('\n========== SAMPLE SUMMARIES ==========')
print()

for i in range(5):
    print(f'--- Sample {i+1} ---')
    print(f'INPUT (first 300 chars):')
    print(eval_samples[i]['input_text'][:300])
    print(f'\nGENERATED SUMMARY:')
    print(predictions[i])
    print(f'\nREFERENCE SUMMARY:')
    print(references[i][:300])
    print(f'\n{"="*60}\n')

========== SAMPLE SUMMARIES ==========

--- Sample 1 ---
INPUT (first 300 chars):
Summarize the following text:
(CNN)Christopher Nowak says none of his friends were surprised when he and his wife decided to use a down payment for a home on a monorail car instead. After all, this was no ordinary monorail car, and Nowak is not your average collector. This was the front cab of an or

GENERATED SUMMARY:
The front cab of an original monorail train that transported millions of visitors throughout Walt Disney World in the 1970s and 1980s . The original Mark IV monorail trains were retired in 1989 to make room for a new generation of models . Nowak, who owns a sound and lighting custom stage design company, said he needed the money to fund their next big project .

REFERENCE SUMMARY:
The listing has been removed from eBay .
The front cab of a Walt Disney World monorail train is on sale on eBay .
The seller is a Disney fan who's not sure whether he's ready to part with it .

============================================================

--- Sample 2 ---
INPUT (first 300 chars):
Summarize the following text:
(CNN)Its a high stakes game of stick or twist with billions of dollars at stake. Traditionally at this time of year, a clutch of nervous owners in charge of struggling clubs in England's top flight grapple with the prospect of relegation, and the enormous hole it threat

GENERATED SUMMARY:
Sunderland's owner Ellis Short fires Uruguayan manager Gus Poyet . The club's owners are trying to protect the $106m it pocketed last season . Aston Villa have scored four unanswered first-half goals in their previous 14 Premier League matches .

REFERENCE SUMMARY:
English Premier League club Sunderland sack Uruguayan manager Gus Poyet .
Heavy home defeat to Aston Villa on Saturday final straw for U.S. owner Ellis Short .
Relegation from English top flight could cost clubs hundreds of millions of dollars .
New EPL television deal due to begin in 2016 worth a s

============================================================

--- Sample 3 ---
INPUT (first 300 chars):
Summarize the following text:
(CNN)Buddy Elias spent much of his life preserving the memory of his cousin Anne Frank. His death Monday brought back memories for me. We met three years ago in an Atlanta hotel conference room. He and his wife, Gerti, were touring the United States to promote a new boo

GENERATED SUMMARY:
"Anne Frank's Family" was published based on 14 boxes of letters, postcards, photos and documents . Elias told me he was lucky that his family had remained in neutral Switzerland when World War II broke out . He was only in seventh grade when his father bought him the book in 1975 .

REFERENCE SUMMARY:
Anne Frank was extremely close to her first cousin Buddy Elias .
A discovery in Elias' attic led to the a book revealing new details about Anne's famiy .
Elias became the preserver of Anne's legacy after her father, Otto Frank, died in 1980 .

============================================================

--- Sample 4 ---
INPUT (first 300 chars):
Summarize the following text:
(CNN)They're some of the toughest athletes on the planet, saying goodbye to loved ones for almost a year, as they traverse the globe's oceans. Hardened Volvo Ocean Race sailors must sleep in four-hour shifts, and survive on little more than freeze dried food and chocola

GENERATED SUMMARY:
Abu Dhabi Ocean Racing skipper Ian Walker speaks about the journey so far . The prestigious competition kicked off from Alicante, Spain, in October last year . This is the 45-year-old Briton's third Volvo Ocean Race .

REFERENCE SUMMARY:
Volvo Ocean Race described as the 'Everest of Sailing'
Seven teams battle on the high seas for nine months .

============================================================

--- Sample 5 ---
INPUT (first 300 chars):
Summarize the following academic text:
-5 mm    many problems in biology , chemistry and material science can be formulated as the study of the energy or free energy landscape of the underlying system .
 well - known examples of such problems include the conformational changes of macromolecules , c

GENERATED SUMMARY:
we report recent work in the field of stochastic differential equations ( sde ) . in this paper , we present a simple example of a system with a gaussian white noise . the system consists of two metastable states , @xmath0 and 1 . we show that the system can overcome the energy barrier between the two states . for this reason , a huge noise term is required to achieve this .

REFERENCE SUMMARY:
many problems in physics , material sciences , chemistry and biology can be abstractly formulated as a system that navigates over a complex energy landscape of high or infinite dimensions .
 well - known examples include phase transitions of condensed matter , conformational changes of biopolymers

============================================================

## Testing on my Own PDF

In [ ]:
!pip install pdfplumber -q
import pdfplumber
import re

def extract_text_from_pdf(file_path):
    full_text = ''
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:
                full_text += text + '\n'
    return full_text

def clean_text(text):
    text = re.sub(r'\n+', '\n', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

from google.colab import files
print('Upload a PDF file to test summarization:')
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
raw_text = extract_text_from_pdf(file_name)
cleaned = clean_text(raw_text)

print(f'\nExtracted {len(cleaned)} characters from {file_name}')
print(f'First 500 chars: {cleaned[:500]}')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 93.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 85.0 MB/s eta 0:00:00
Upload a PDF file to test summarization:

Saving IGCSE-Biology-Notes.pdf to IGCSE-Biology-Notes.pdf

Extracted 54897 characters from IGCSE-Biology-Notes.pdf
First 500 chars: whatsapp: +92 323 509 4443, email: megalecture@gmail.com IGCSE B i o l o g y m o No t es c . e r u t c e l a g e m . w w w Refined by KmQ Unit 1 : Characteristics of living things www.youtube.com/megalecture Page 1 of 50 whatsapp: +92 323 509 4443, email: megalecture@gmail.com Biology is the study of living organisms. For something to be alive it needs to perform all seven functions of living things.MRS GREN Movement, Respiration, Sensitivity, Growth, Reproduction, Excretion, Nutrition. 1. Movem

In [ ]:
def summarize_long_text(text, chunk_size=1500, max_summary_length=200):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size):
        chunk = ' '.join(words[i:i + chunk_size])
        chunks.append(chunk)

    print(f'Document split into {len(chunks)} chunks')

    chunk_summaries = []
    for i, chunk in enumerate(chunks):
        input_text = 'Summarize the following academic text:\n' + chunk
        inputs = tokenizer(input_text, max_length=MAX_INPUT_LENGTH, truncation=True, return_tensors='pt').to(device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_length=max_summary_length,
                min_length=30,
                num_beams=4,
                length_penalty=1.0,
                no_repeat_ngram_size=3,
                early_stopping=True
            )

        summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
        chunk_summaries.append(summary)
        print(f'  Chunk {i+1}/{len(chunks)} summarized')

    if len(chunk_summaries) > 1:
        combined = ' '.join(chunk_summaries)
        input_text = 'Summarize the following text into a coherent summary:\n' + combined
        inputs = tokenizer(input_text, max_length=MAX_INPUT_LENGTH, truncation=True, return_tensors='pt').to(device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_length=300,
                min_length=50,
                num_beams=4,
                length_penalty=1.0,
                no_repeat_ngram_size=3,
                early_stopping=True
            )

        final_summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
    else:
        final_summary = chunk_summaries[0]

    return final_summary, chunk_summaries

final_summary, chunk_sums = summarize_long_text(cleaned)



if len(chunk_sums) > 1:
    print(f'\n--- Individual Chunk Summaries ({len(chunk_sums)} chunks) ---')
    for i, cs in enumerate(chunk_sums):
        print(f'\nChunk {i+1}: {cs}')

In [ ]:
FINAL_MODEL_DIR = f'{SAVE_DIR}/final_model'
os.makedirs(FINAL_MODEL_DIR, exist_ok=True)

model.save_pretrained(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

print(f'Model saved to: {FINAL_MODEL_DIR}')
print(f'\nFiles saved:')
for f in os.listdir(FINAL_MODEL_DIR):
    size = os.path.getsize(f'{FINAL_MODEL_DIR}/{f}') / 1024 / 1024
    print(f'  {f} ({size:.1f} MB)')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to: /content/drive/MyDrive/EduAI_Models/summarizer/final_model

Files saved:
  config.json (0.0 MB)
  generation_config.json (0.0 MB)
  model.safetensors (944.5 MB)
  tokenizer_config.json (0.0 MB)
  tokenizer.json (2.3 MB)

In [ ]:
!cd /content/drive/MyDrive/EduAI_Models/summarizer && zip -r /content/eduai_summarizer_final.zip ./final_model

from google.colab import files
files.download('/content/eduai_summarizer_final.zip')